insert into rating (c_id, d_id, type, dor, rating, comments) values (407, 19, 'C', '21-May-2021', 3, 'Cras pellentesque volutpat dui.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (273, 16, 'C', '05-Aug-2021', 1, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (834, 7, 'D', '18-Nov-2021', 1, 'Etiam faucibus cursus urna.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (532, 24, 'C', '22-Sep-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (900, 9, 'C', '26-Aug-2021', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (769, 21, 'C', '10-Feb-2022', 4, 'Proin eu mi.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (660, 24, 'D', '27-Feb-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (105, 29, 'D', '18-Nov-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (841, 8, 'D', '14-Sep-2021', 1, 'Phasellus in felis.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (748, 20, 'D', '03-Jul-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (310, 14, 'D', '13-Jun-2021', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (428, 16, 'D', '16-Jul-2021', 3, 'Maecenas tincidunt lacus at velit.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (532, 25, 'C', '18-Jan-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (186, 20, 'D', '20-Jun-2021', 5, 'In blandit ultrices enim.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (466, 10, 'D', '10-Apr-2022', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (841, 26, 'D', '11-Feb-2022', 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (420, 14, 'D', '26-Oct-2021', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (518, 8, 'D', '26-Jul-2021', 4, 'Nullam porttitor lacus at turpis.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (662, 23, 'D', '14-May-2021', 1, 'Mauris lacinia sapien quis libero.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (771, 5, 'D', '17-Mar-2022', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (273, 27, 'C', '08-Apr-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (746, 3, 'D', '21-Mar-2022', 1, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (411, 27, 'D', '27-Jan-2022', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (947, 9, 'C', '25-Oct-2021', 5, 'Nunc purus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (769, 1, 'C', '10-Aug-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (941, 3, 'C', '16-Dec-2021', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (466, 12, 'D', '18-Feb-2022', 5, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (740, 24, 'D', '28-Oct-2021', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (962, 2, 'C', '01-Feb-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (518, 24, 'C', '09-Jul-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (318, 17, 'C', '22-Mar-2022', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (732, 30, 'D', '03-Jun-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (318, 25, 'C', '31-Oct-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (872, 19, 'C', '03-Mar-2022', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (310, 29, 'C', '02-Apr-2022', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (941, 7, 'C', '04-Jul-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (563, 10, 'D', '17-Dec-2021', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (130, 18, 'C', '21-May-2021', 2, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (625, 11, 'D', '19-Dec-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (625, 26, 'C', '19-May-2021', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (834, 29, 'D', '11-Nov-2021', 1, 'Donec ut mauris eget massa tempor convallis.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (395, 17, 'C', '07-Apr-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (732, 9, 'C', '15-Nov-2021', 3, 'Donec ut dolor.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (915, 15, 'D', '09-Jul-2021', 3, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (816, 23, 'C', '06-Sep-2021', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (570, 15, 'C', '24-Jun-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (570, 17, 'D', '05-Jul-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (130, 23, 'C', '05-Aug-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (466, 22, 'C', '03-Jan-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (386, 12, 'D', '11-Aug-2021', 1, 'Donec vitae nisi.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (128, 11, 'D', '07-Jun-2021', 2, 'Nam dui.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (488, 14, 'D', '12-Feb-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (767, 20, 'D', '12-Apr-2022', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (466, 5, 'C', '29-Apr-2022', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (310, 28, 'D', '12-Apr-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (557, 16, 'C', '09-Mar-2022', 2, 'Cras in purus eu magna vulputate luctus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (660, 26, 'C', '17-Apr-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (385, 8, 'C', '12-Dec-2021', 4, 'In sagittis dui vel nisl.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (900, 18, 'C', '20-Feb-2022', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (340, 3, 'C', '23-Mar-2022', 1, 'Aliquam erat volutpat.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (746, 4, 'D', '16-Aug-2021', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (320, 12, 'D', '10-Feb-2022', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (105, 8, 'C', '01-Feb-2022', 1, 'Vivamus in felis eu sapien cursus vestibulum.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (400, 11, 'D', '30-Jan-2022', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (740, 22, 'C', '08-Jun-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (194, 9, 'C', '07-Jan-2022', 1, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (360, 6, 'C', '02-Dec-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (557, 15, 'C', '19-May-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (769, 8, 'C', '14-Sep-2021', 1, 'Maecenas pulvinar lobortis est.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (529, 17, 'C', '04-Feb-2022', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (869, 8, 'D', '18-Jun-2021', 5, 'Donec ut dolor.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (530, 30, 'C', '20-Jan-2022', 3, 'Aenean lectus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (318, 11, 'D', '11-Apr-2022', 4, 'Nam dui.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (318, 20, 'C', '18-Feb-2022', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (549, 23, 'C', '10-Jan-2022', 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (155, 24, 'C', '01-May-2022', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (782, 11, 'C', '06-Oct-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (771, 2, 'D', '13-Jan-2022', 2, 'Aliquam non mauris.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (660, 20, 'D', '28-Dec-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (563, 9, 'D', '31-Dec-2021', 4, 'Curabitur convallis.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (557, 3, 'C', '21-May-2021', 1, 'Nulla justo.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (507, 8, 'C', '11-Nov-2021', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (915, 19, 'C', '18-Jul-2021', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (750, 19, 'C', '26-Oct-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (980, 2, 'C', '26-Oct-2021', 5, 'Vivamus tortor.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (601, 11, 'D', '06-Sep-2021', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (506, 5, 'C', '12-Jul-2021', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (627, 14, 'D', '24-Oct-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (488, 24, 'D', '25-Oct-2021', 4, 'Praesent lectus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (478, 11, 'D', '19-Apr-2022', 1, 'Quisque ut erat.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (834, 14, 'C', '21-Nov-2021', 4, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (478, 20, 'C', '31-Oct-2021', 1, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (834, 16, 'D', '30-Oct-2021', 5, 'Integer ac leo.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (674, 7, 'D', '06-Jul-2021', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (198, 21, 'D', '06-Jan-2022', 5, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (190, 27, 'C', '26-Jun-2021', 2, 'Nullam molestie nibh in lectus.');
insert into rating (c_id, d_id, type, dor, rating, comments) values (407, 22, 'D', '02-Apr-2022', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (420, 10, 'C', '09-Jul-2021', 2, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (941, 7, 'C', '10-Oct-2021', 3, null);
insert into rating (c_id, d_id, type, dor, rating, comments) values (767, 28, 'D', '16-Dec-2021', 2, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
