insert into vehicle (d_id, vno, model, category, fuel_type, color) values (1, 'WBAYE4C58ED412232', 'Civic', 'Sedan', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (2, 'JN1BY1AP6FM597369', 'Murciélago', 'Sedan', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (3, '5UXZW0C50CL033398', 'V8 Vantage', 'Sedan', 'Petrol/CNG', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (4, 'KMHFH4JG7FA563745', 'G5', 'Hatchback', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (5, '1GYEE637970361878', 'Sonoma', 'Sedan', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (6, 'WAUMGBFLXAA270985', 'Crown Victoria', 'Hatchback', 'Petrol/CNG', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (7, 'WAULT58E32A324068', 'GTI', 'SUV', 'Diesel', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (8, 'WDDLJ7DB4DA650020', 'Continental', 'Sedan', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (9, 'WBXPA73414W312174', 'Mulsanne', 'SUV', 'Petrol/CNG', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (10, '1G6DG8E3XE0579359', 'S-Series', 'SUV', 'Petrol/CNG', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (11, 'WBALL5C50CJ841482', 'SLK-Class', 'SUV', 'Diesel', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (12, 'JM3KE2BE2F0795437', 'Camaro', 'Sedan', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (13, '1C3BCBGG3CN260144', 'Viper', 'Hatchback', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (14, '2HNYD18602H309482', 'Passport', 'SUV', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (15, '3VW507AT8FM728434', 'tC', 'Hatchback', 'Diesel', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (16, '5GAKVAED6CJ335193', 'Caravan', 'Sedan', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (17, 'WBAYF8C50ED545748', 'Familia', 'SUV', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (18, 'KNADH5A30A6504804', 'Truck', 'Sedan', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (19, 'WBAUC9C56DV959171', 'Maxima', 'SUV', 'Diesel', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (20, '1GD11ZCG0DF050670', 'Armada', 'SUV', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (21, '4A31K3DT3CE663359', 'S-Type', 'SUV', 'Petrol/CNG', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (22, 'JN1CV6EK6CM970401', 'Bravada', 'SUV', 'Diesel', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (23, '3C4PDDEG7CT515665', 'Grand Vitara', 'Hatchback', 'Diesel', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (24, '3GYFNGEY3BS040131', 'Wrangler', 'SUV', 'Diesel', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (25, 'WAUML64B93N432520', 'Sky', 'Hatchback', 'Petrol/CNG', 'Silver');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (26, 'WP0AA2A93AS356247', 'Arnage', 'SUV', 'Diesel', 'White');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (27, 'WBA3R5C56FK859790', 'EX', 'Sedan', 'Diesel', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (28, 'WBAWL1C54AP710295', 'Elantra', 'Hatchback', 'Diesel', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (29, '1FTSW2A59AE870179', 'Yukon', 'Sedan', 'Petrol/CNG', 'Black');
insert into vehicle (d_id, vno, model, category, fuel_type, color) values (30, 'WP0AB2A84FK230782', 'Flying Spur', 'Hatchback', 'Petrol/CNG', 'Black');
